kind: pipeline
name: testing

clone:
  depth: 1

steps:
  - name: testing
    image: golang:1.12
    pull: true
    environment:
      GO111MODULE: on
    commands:
      - go test -v -bench=Master -benchmem
      - go test -v -bench=Route -benchmem
