kind: pipeline
name: testing

workspace:
  base: /go
  path: src/github.com/appleboy/golang-graphql-benchmark

clone:
  depth: 50

steps:
  - name: testing
    image: golang:1.11
    pull: true
    environment:
      GO111MODULE: off
    commands:
      - go test -v -bench=Master -benchmem
      - go test -v -bench=Route -benchmem
